### ISSUE TITLE
Bug: Red Alarm Crashes on New 3DS XL

### ISSUE THREAD

**Issue by ChrisHighwind** [skyfloogle/red-viper#1]
As the title says, Red Alarm has a tendency to crash when playing. Usually I've had it crash during the face miniboss in Stage 1, but I did manage to make it to Stage 2 once before it crashed.

I'm unsure of the cause of this crash, but I will state that I am playing on a New 3DS XL running Luma3DS v13.0.2 with the 3D on.

~~I also have "Redirect app. syscore threads to core2" turned on, will test with that off just to see if that affects anything.~~ EDIT: Red Alarm still crashed with this turned off in the Luma settings.

**Comment by soup244** [comment]
It happens on standard O3DS as well

**Comment by Nintoad** [comment]
Same here on New 3DS XL. The emulator does not crash or freeze, the gameplay just freezes with the sound still going.

**Comment by ChrisHighwind** [comment]
@Nintoad I've had a range of crashes. Sometimes the gameplay would freeze with the sound still going like you said, sometimes it'd freeze with the sound either cutting off or hanging on one note, and sometimes I'd get the graphical garbage type of crash.

**Comment by shubshub** [comment]
![image](https://github.com/skyfloogle/red-viper/assets/413964/aa7ffdda-8975-4fd6-b37a-b8f0a0f243bf)
While playing Red Alarm first the game froze up on me midway through Stage 1 and then the second time the above happened

**Comment by glowblue** [comment]
On New 3DS XL, got a crash after the Stage 1 boss. Error message on lower screen said: 
**DRC error #2
PC=0x00006ee2
Dumping debug info...

Press any key to exit**

Let me know if the debug dump would be helpful and I can send it if you can tell me where that's saved. 

Every other game has been running great, this emulator is fantastic! Thanks so much, devs!

**Comment by SwitchaRoozy** [comment]
I can confirm that Red Alarm crashes on my N3DSXL as well. Sometimes it's a freeze with a crash dump message on the bottom screen. Other times, it's just garbled graphics. It's not in the same place each time, but I can't get to level 2.

Otherwise, this is a really good emulator! It would be so great if this was fixed because ironically, this and Tetris 3D, which also has problems, are probably my favorite VB games lol.

**Comment by ChrisHighwind** [comment]
Can confirm that commit 779d8d3 fixed the issue. I was able to get to Stage 5 when I died to the boss and decided to end the run at that point. Thanks so much!

**Comment by Screamliner** [comment]
> Can confirm that commit 779d8d3 fixed the issue. I was able to get to Stage 5 when I died to the boss and decided to end the run at that point. Thanks so much!

do you mind share the cia file you build? Because people like me can’t build it by themselves can only wait for updates. 😂😂😂

**Comment by skyfloogle** [comment]
Bleeding-edge builds are available through GitHub Actions. [Here's](https://github.com/skyfloogle/red-viper/actions/runs/8117992469) the latest one.

**Comment by Screamliner** [comment]
> Bleeding-edge builds are available through GitHub Actions. [Here's](https://github.com/skyfloogle/red-viper/actions/runs/8117992469) the latest one.

OH~ Thank you!!

**Comment by glowblue** [comment]
Thank you. I managed to build the 3dsx, but building the cia bugged out because I was on Mac and it was looking for a "makerom-mac" file that didn't exist.

**Comment by Nintoad** [comment]
> Can confirm that commit [779d8d3](https://github.com/skyfloogle/red-viper/commit/779d8d39c7bcd34f6315a6d4a7a280922f47d5d6) fixed the issue. I was able to get to Stage 5 when I died to the boss and decided to end the run at that point. Thanks so much!
> 
> EDIT: I applied a patch to make it easier to access the Debug Menu in Red Alarm, and with the Special option contained within, I was able to play the game from start to finish with no lockups or crashes.

Way better than me. I have not managed to get past the Stage 3 boss, but now it's because of sucking not crashing. Glad to see it fixed, this emulator is so great! Can't imagine why Nintendo did not at the very least put out VB Wario Land on 3DS.
