### ISSUE TITLE
Suggestion: Add this emulator to Universal-DB

### ISSUE THREAD

**Issue by JLO64** [skyfloogle/red-viper#12]
I know this isn't exactly a big issue given that this emulator is easily installable via the .CIA and .3DSX files, but I think having the option to install it via Universal Updater would be ideal. Not only would it allow for more users to discover it, but it would also ensure that more people download future updates of the app.

**Comment by eliaskma** [comment]
good idea, but it would make more sense to put version 1.0 or later on there

**Comment by skyfloogle** [comment]
Sent them a request: https://github.com/Universal-Team/db/issues/191

**Comment by skyfloogle** [comment]
https://db.universal-team.net/3ds/red-viper
