### ISSUE TITLE
Suggestion: Option to choose which eye view is default

### ISSUE THREAD

**Issue by SuperfieldCU** [skyfloogle/red-viper#13]
Virtual Boy always outputted two images: one for the left eye and one for the right eye. Red Viper, when the depth is turned off, currently shows just the right eye information. It would be nice if the user could choose which one is the one used when the 3D is turned off (or unavailable, for our 2DS users).

**Comment by skyfloogle** [comment]
Added in 7d6cd84 (I keep forgetting to connect the commit to the issue)
