### ISSUE TITLE
Software won't close

### ISSUE THREAD

**Issue by WolfKitten** [skyfloogle/red-viper#16]
On my new 3ds, the software takes so long to close, im convinced the system froze and I it power off. Not sure if this is normal for now or not.

**Comment by skyfloogle** [comment]
I've seen this a few times during development, though I always thought it was because I had gdb attached. Did you close via the Home menu or through the exit button in the emulator?

**Comment by WolfKitten** [comment]
I close it through the home menu, I haven't tried closing It through the button in the menu tbh

**Comment by pmsobrado** [comment]
@skyfloogle When closing from home menu, I get a crash every time, with no ROM loaded. Running the CIA, not the 3DSX. Not a big deal, but it would be nice to exit cleanly with home menu.

The quit button on the emulator itself works fine.

Quitting the 3DSX from both quit and home menu (although I'm technically exiting Homebrew Channel there) works fine. To be honest, the 3DSX I have is compiled from djedditt fork with custom 3D depth support, although that should not matter.

I can upload the dump of the crash if you want.

Thanks.

**Comment by skyfloogle** [comment]
df0de92 should fix the crash, but I'll keep the issue open since the crash looks like a separate issue.

**Comment by pmsobrado** [comment]
Will you release a test build, or should I compile this myself?

**Comment by skyfloogle** [comment]
You can grab a build off GH Actions: https://github.com/skyfloogle/red-viper/actions/runs/8071897719

**Comment by pmsobrado** [comment]
It works fine, you can include it on the next stable release I guess.

**Comment by Stingray77** [comment]
Had the same issue; thanks for fixing.
