### ISSUE TITLE
Error: couldn't initialize audio

### ISSUE THREAD

**Issue by blackwavesofenergy** [skyfloogle/red-viper#17]
Get this error message which means there's no audio. I've already dumped my DSP firmware so not sure what's going on.

![error](https://github.com/skyfloogle/red-viper/assets/122287423/15ef6ab7-176f-4398-a7f8-a09f6dc33da9)

**Comment by toastydepression** [comment]
I got the same error, I just reinstalled DSP1/DSP2 again and redumped the DSP, works perfectly now.

**Comment by pmsobrado** [comment]
Duplicate of https://github.com/skyfloogle/red-viper/issues/3.

**Comment by skyfloogle** [comment]
Did you manage to resolve the issue? What Luma version are you on? @blackwavesofenergy

**Comment by blackwavesofenergy** [comment]
Yes, I managed to solve the problem by updating Luma. It seems older Luma versions won't work, even when the DSP is installed.
