### ISSUE TITLE
QR code for easy installation

### ISSUE THREAD

**Issue by perguto** [skyfloogle/red-viper#20]
Please add a  qr code for the .cia download link so people can easily install it via FBI's remote install function.

**Comment by Sakitoshi** [comment]
skill issue.
1. go to https://www.the-qrcode-generator.com/
2. paste link
3. ??
4. profit
you are welcome.

**Comment by LuaGunsX** [comment]
![image](https://github.com/skyfloogle/red-viper/assets/134158550/6f22b6d9-c691-476e-8c85-0838c64ad61b)
there you go.

**Comment by JeffRuLz** [comment]
Vague Rant on gbatemp posted a qr code that points to the most recent version on github. This one will always be up to date.
https://gbatemp.net/threads/new-virtual-boy-emulator-red-viper-for-3ds-released-with-full-3d-support.649481/page-3#post-10365914
![red-viper-cia](https://github.com/skyfloogle/red-viper/assets/14222721/c50bac22-88fc-4571-8e75-8b51fd898335)

**Comment by skyfloogle** [comment]
Thanks, added to readme!
