### ISSUE TITLE
Zip file support?

### ISSUE THREAD

**Issue by shubshub** [skyfloogle/red-viper#22]
Would be nice to be able to store zip file of a rom and it decompresses at load time, The roms arent that big so should be fine right?

**Comment by CCCP1982** [comment]
Why launch them from ZIP if the weight of the games is mere pennies?

**Comment by CCCP1982** [comment]
> Why launch them from ZIP if the weight of the games is mere pennies?


Why launch them from ZIP if the weight of the games is mere pennies?
