### ISSUE TITLE
Crashed when entering home screen

### ISSUE THREAD

**Issue by DragonKnightKX** [skyfloogle/red-viper#23]
I went to close the emulator by pressing the home button. Just about a second later, the system crashed. It doesn't seem to have done any damage, but it was certainly a scare.

**Comment by skyfloogle** [comment]
I believe this was fixed as a side issue that was brought up in the comments on #16. Does the issue still occur when downloading one of these builds? https://github.com/skyfloogle/red-viper/actions/runs/8086110834

**Comment by DragonKnightKX** [comment]
Downloading that build seems to have fixed it, thank you.
