### ISSUE TITLE
Sound issue, what to do?

### ISSUE THREAD

**Issue by Nanakix** [skyfloogle/red-viper#3]
![PXL_20240225_233853958](https://github.com/skyfloogle/red-viper/assets/10825980/b20094ea-c228-4b16-b3e2-9963066ab3a7)

Happened on a new 2DS XL and new 3DS running under different CFW updates, one with arm9loaderx and the other one on luma (but not up to date).

This is not a crash, but I'd like to play with the sound on 😄 
Is there a documentation to fix this ? :)

**Comment by Nanakix** [comment]
Auto resolving my issue: Reinstalling latest luma and cfw updates fixed this.

**Comment by sli** [comment]
For anyone still having the issue: a Luma update alone won't do it if you haven't dumped your DSP firmware.

Open the Luma menu with L+Down+Select, scroll down to Miscellaneous Options, then select Dump DSP Firmware. The screen will go black for a bit, then report that it's written the firmware. The emulator's sound will now function.

**Comment by skyfloogle** [comment]
@Nanakix Do you remember what version you were on previously? It seems useful to figure out what minimum version is necessary.
