### ISSUE TITLE
Sudden Freeze/Hard crash on Tetris 3D

### ISSUE THREAD

**Issue by beatcathackz** [skyfloogle/red-viper#37]
Have been using this emulator for a while. Every once in a while, I‘m playing 3D Tetris, and a/v crashes, and the entire system stops responding.  New3DSXL if you need the model.

**Comment by mariokorte** [comment]
Had the same problem several times with this game while the title screen animation ran. When i skipped the animation quite soon I had no problems so far.

**Comment by skyfloogle** [comment]
Are you guys on 0.9.1? I fixed various random 3D Tetris crashes there.

**Comment by mariokorte** [comment]
You're right. seems a lot more stable with 0.9.1. thanks a lot!
