### ISSUE TITLE
Suggestion: Alternative input on ROM picker

### ISSUE THREAD

**Issue by SpiceWare** [skyfloogle/red-viper#42]
First off - awesome job! I know what's involved with these as I've been involved with Stella (Atari 2600 emulator) since the 90s when I ported it to OS/2.

I find the ROM picker to be very touchy - inevitably I'll accidentally launch a ROM while swiping up/down to scroll to a specific game.

I suspect part of the issue is I'm using my finger, instead of a stylus, to scroll the list. I use an after market grip/handle on my 3DS else my hands cramp, and the grip blocks access to the stylus slot.

If possible could the ROM picker be updated to also support the D pad and A/B buttons to maneuver thru the directory structure, select a game, and launch it?

Thanks!

**Comment by skyfloogle** [comment]
Resolved in #47
