### ISSUE TITLE
DSP1 audio help

### ISSUE THREAD

**Issue by theboy181** [skyfloogle/red-viper#49]
Red Viper is complaining that it doesn't have audio, and if I try to load any game without sound it will freeze when you load a rom.

I dumped my audio with DSP1 3DS and it still doesn't detect the audio.

What do I need to do?

**Comment by skyfloogle** [comment]
What version of Luma3DS are you on? Updating might help.

**Comment by CCCP1982** [comment]
> What version of Luma3DS are you on? Updating might help.

And what should be the Lumia 3DS version?

**Comment by theboy181** [comment]
I am running on a NEW3DSXL

Its been a while since I used this, this is one reason it came out of my closet.

Without a sd card inserted when I hold the select button while booting I get Luma v6.6

In the system settings menu I see SYS 11.2.0+35U

I am not sure how the 3ds is loading into luma without the sd card. Its been a very long time since I rooted this device.

**Comment by skyfloogle** [comment]
Luma 6 is ancient, I'm not sure what the minimum version is but a bunch of relevant stuff was added in 8, and they're on 13 now. Upgrading should fix it.

**Comment by CCCP1982** [comment]
3DS XL
![trashed-1712969304-IMG_20240314_034751](https://github.com/skyfloogle/red-viper/assets/142115581/d0a8d00f-1bbd-4384-b437-0343c615d653)
![IMG_20240314_034833](https://github.com/skyfloogle/red-viper/assets/142115581/8c764d72-490f-4ad6-afc4-f4f6244ddb0d)

**Comment by CCCP1982** [comment]
> I am running on a NEW3DSXL
> 
Now I understand why my emulator runs so well. The latest version is 13.0.2.

**Comment by CCCP1982** [comment]
> I am running on a NEW3DSXL
> 
> Its been a while since I used this, this is one reason it came out of my closet.
> 
> Without a sd card inserted when I hold the select button while booting I get Luma v6.6
> 
> In the system settings menu I see SYS 11.2.0+35U
> 
> I am not sure how the 3ds is loading into luma without the sd card. Its been a very long time since I rooted this device.

Now I understand why my emulator runs so well. The latest version is 13.0.2.

**Comment by skyfloogle** [comment]
Gonna assume this was resolved by upgrading, let me know if I'm mistaken.
