### ISSUE TITLE
[Suggestion] Put the savestates in the 3ds folder

### ISSUE THREAD

**Issue by Anonymous941** [skyfloogle/red-viper#62]
I prefer to have homebrew use the 3ds folder as it reduces clutter and allows quickly backing up the homebrew data without backing up the other things on the SD card (eg NAND backups).  Could this be considered for Red Viper's savestates, or at least could it search for the folder's existence and use that if it exists?

**Comment by skyfloogle** [comment]
After running [the latest build](https://github.com/skyfloogle/red-viper/actions/runs/8959269610), you can update Red Viper's home path in the config file. I intend to eventually use this directory for other things as well.

**Comment by Anonymous941** [comment]
Thank you!  Of course, there's the the configuration file itself, but I think I'll just edit that when I compile it lol
