### ISSUE TITLE
n3DS ZL/ZR alternate toggle use suggestion

### ISSUE THREAD

**Issue by riggles1** [skyfloogle/red-viper#64]
For both VB Wario Land and Mario Clash you hold L or R in order to run, meaning that you're really holding these down throughout the entire playthrough with no real reason to let them go. Holding these down uninterrupted for so long can get uncomfortable.

It would be nice to have ZL/ZR have an alternative toggle mapping where instead of working as A/B, they can work as L/R toggles. 
- Press ZR once, R stays registered as continually pressed down until ZR is pressed again (pressing R should also unstick it).

As far as visually getting this function across within the UI, maybe have some sort of switch icon as you choose between these:
- (L) (B) (A) (R) -, - (L) (A) (B) (R) -, - (A) (L) (R) (B) -, - (B) (L) (R) (A) -, and the new one - (L) {L} {R} (R) -

Just a suggestion and no big deal, just close this request if it's not worth implementing. Thanks!

**Comment by skyfloogle** [comment]
The custom control mapper added in recent commits has toggle support.
