### ISSUE TITLE
[Suggestion] Frame/flicker blend?

### ISSUE THREAD

**Issue by TonchMS** [skyfloogle/red-viper#69]
I've noticed that in particular, Galactic Pinball has static table elements that flicker on and off every frame to simulate transparency (a good example is the UFO table). If I play a table for too long and then quit, that element will be temporarily burned into the home screen, causing a lasting flicker effect in its wake. My top screen is an IPS one, which are well known for flaws like this, so I'm sure it's not cause for alarm, but still...

Is it possible to implement an optional toggle for a frame blend like, for instance, the Analog Pocket has? This would remove the flicker and better simulate transparency, and ideally wouldn't add _much_ blur if it's subtle enough.

Keep up the great work!

**Comment by skyfloogle** [comment]
Good thought. Added in b2889ae and other recent commits. Current and previous frames are blended 50%.
