### ISSUE TITLE
Jack Bros. freezing after credits

### ISSUE THREAD

**Issue by drakarthus** [skyfloogle/red-viper#71]
So, I beat Jack Bros. and after the credits roll, just before the moment the "THE END" text should appear next to Atlus's logo on the ending screen, the game just freezes and won't actually end properly, yet Red Viper itself seems to still work fine when that happens, as I'm still able to load savestates and change settings just fine (tested on v0.9.6 on an Old 3DS XL).

I also tried reloading a previous savestate and beating the boss again, and the game froze in all 3 of my attempts.

Here are the debug files I've got from the emulator after the game froze, as well as my savestates just before the final bossfight (st7) and at the start of the ending cutscene (st8).

[debug.zip](https://github.com/user-attachments/files/15948500/debug.zip)

**Comment by skyfloogle** [comment]
Hi! Sorry, my notifications weren't set up right so I missed a bunch of GitHub issues over the past few months.
I've investigated this, and surprisingly, this appears to be intended behaviour - I've even replicated this on my Virtual Boy. All the sources on the Internet say that the ending depends on whether you have at least 3 special attacks left, but after what I've seen, I suspect you're also locked out of the good ending if you use passwords.
