### ISSUE TITLE
unable to build from source due to ini.h dependency

### ISSUE THREAD

**Issue by queenbiscuit311** [skyfloogle/red-viper#9]
Sorry if this is a stupid question since im not very experienced with dealing with source code, but when building from source I get this error:

`red-viper/source/common/vb_set.c:8:10: fatal error: inih/ini.h: No such file or directory`

In an attempt to fix this, i installed the inih packages from my package manager, but the error persists. I went to see where the makefile sources the include directories, and I put the ini.h headers in /opt/devkitpro/ibctru/inih and it gives me a different, still inih related error while building. Am i missing a package or something? I can't seem to find any devkitpro package with inih and running "git submodule update" does not appear to do anything.

I feel like I'm missing something obvious but i didn't know how else to figure it out than open an issue. Tried building on both msys2 ucrt64 and arch linux.

**Comment by JeffRuLz** [comment]
Inih's source files belong in "red-viper/source/common/inih/"
https://github.com/skyfloogle/red-viper/tree/master/source/common

**Comment by queenbiscuit311** [comment]
Seems like that's not being pulled for me. ill try doing it manually

**Comment by Thysbelon** [comment]
Try running `git submodule update --init --recursive` in the cloned red-viper directory. It worked for me. I learned that command from this [webpage explaining git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by queenbiscuit311** [comment]
yup that was it, thanks.

> Try running `git submodule update --init --recursive` in the cloned red-viper directory. It worked for me. I learned that command from this [webpage explaining git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).
